name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u jeremycardona --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/jeremycardona/docker-hello-world:latest \
            --push .

